# Generated by Django 4.2.4 on 2024-04-12 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0020_remove_article_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 12, 48, 145784)),
        ),
    ]
