# Generated by Django 4.2.4 on 2024-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapmarker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mapmarker',
            name='name',
        ),
        migrations.AddField(
            model_name='mapmarker',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
