# Generated by Django 4.2.4 on 2024-04-21 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0021_alter_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 31, 47, 652602)),
        ),
    ]
