# Generated by Django 4.2.4 on 2024-05-24 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0022_article_image_alter_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 7, 7, 23, 990344)),
        ),
    ]
