# Generated by Django 4.2.4 on 2024-04-08 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='sendTo',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='sendFrom',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
