# Generated by Django 4.2.4 on 2024-04-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_rename_sendto_chatbot_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'ordering': ['-datetime']},
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='created',
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to=settings.AUTH_USER_MODEL, verbose_name='Suggested by')),
            ],
        ),
    ]
