# Generated by Django 4.2.4 on 2024-04-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatbot_options_remove_chatbot_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'ordering': ['-dateTime']},
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='datetime',
            new_name='dateTime',
        ),
    ]
