# Generated by Django 4.2.4 on 2024-04-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chatbot_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
