# Generated by Django 4.2.4 on 2024-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyButton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyButtonn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyButton',
        ),
    ]
