# Generated by Django 4.2.4 on 2024-03-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyButton', '0002_emergencybuttonn_delete_emergencybutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyButtonn',
        ),
    ]
